version: "2"
services:
    www:
        build: .
        ports: 
            - "8086:80"
        volumes:
            - ./web:/var/www/html/
        networks:
            - default
volumes:
    persistent: